### ISSUE TITLE
Open button in notification doesn't do anything

### ISSUE THREAD

**Issue by vadi2** [gematik/codfsh#19]
The open button in this notification doesn't seem to have an effect:

<img width="504" alt="image" src="https://github.com/gematik/codfsh/assets/110988/4bf9d1b9-a928-47c8-9e10-58092af930f9">

Personally the notification doesn't seem all that necessary, since you are expecting a result of some kind anyway having started the validate operation just a few seconds ago.

**Comment by SvenSommer** [comment]
Thank you @vadi2 for your feedback.

You're correct, the notification might be a bit redundant since users would expect a result after triggering the validation operation. As per your feedback, I've removed the popup with the 'Open' button for the processed file.

This change will be reflected in the upcoming version (1.0.8) of the extension. Please update the extension when the new version is released and feel free to provide any additional feedback you might have.
